# We set KERN_ALERT here because we don't want printing before Plymouth.
# The log level is increased to 4 (the default) after Plymouth comes up
# or if nosplash is set.
loglevel=1
vt.global_cursor_default=0
# TODO: remove when no kernel has CONFIG_LOGO=y
logo.nologo
