[lint]
# These are fixed in pmaports main, but we can't easily backport the patch
# because CI for the two branches has become too different. Ignore the liniting
# errors on v26.06.
ignore = [
  "BLE001",
  "C401",
  "C408",
  "DTZ011",
  "EXE001",
  "F401",
  "FURB105",
  "FURB129",
  "FURB188",
  "I001",
  "LOG015",
  "PIE810",
  "PLR1722",
  "SIM102",
  "SIM115",
  "UP021",
]
