[LightDM]
logind-check-graphical=false

[Seat:*]
user-session=honor6x-xfce
xserver-command=/usr/libexec/Xorg -modulepath /usr/lib/honor6x/xorg/modules,/usr/lib/xorg/modules -nolisten tcp -novtswitch -sharevts -keeptty
display-setup-script=/usr/sbin/honor6x-display-setup
allow-guest=false
