# os-release MUST point to the version in the slot during boot or else confext
# (and other things) fail version checks. This is critical, a mismatch in versions
# can break booting the system. The '+' after 'L' means "remove a non-symlink
# and then create the symlink."
L+ /etc/os-release - - - - ../usr/lib/os-release
