# openssh expects this dir to exist
d /var/empty 0755 root root -
# Busybox crontab expects this dir to exist and have a symlink to /etc/crontabs/
d /var/spool/cron 0755 root root -
d /etc/crontabs 0755 root root -
L /var/spool/cron/crontabs - - - - /etc/crontabs/
