[preset 0]
no_display

[preset 1]
frame_timing=0
cpu_stats=0
gpu_stats=0
fps=1
fps_only
legacy_layout=0
width=40
frametime=0

[preset 2]
legacy_layout=0
horizontal
cpu_stats
gpu_stats
ram
fps
frametime=0
hud_no_margin
table_columns=14
frame_timing=1

[preset 3]
cpu_temp
gpu_temp
ram
proc_vram
io_read
io_write
wine
fex_stats=status+apptype+jitload+sigbus+smc+softfloat
frametime

[preset 4]
full
fex_stats=status+apptype+hot_threads+jitload+sigbus+smc+softfloat

