# Wi-Fi only tablet: hide WWAN, cellular and mobile-data widgets.

[sm/puri/phosh/plugins]
quick-settings=['location-quick-setting', 'dark-mode-quick-setting', 'night-light-quick-setting', 'scaling-quick-setting', 'caffeine-quick-setting']

[org/gnome/settings-daemon/plugins/wwan]
active=false

[org/gnome/settings-daemon/peripherals/touchscreen]
orientation-lock=true

[org/gnome/desktop/input-sources]
sources=[('xkb', 'us')]

[org/gnome/desktop/interface]
font-name='Cantarell 11'
document-font-name='Cantarell 11'
monospace-font-name='Noto Sans Mono 11'
font-antialiasing='grayscale'
font-hinting='slight'
text-scaling-factor=1.0
