# App drawer folders.

[org/gnome/desktop/app-folders]
folder-children=['Media', 'Utilities']

[org/gnome/desktop/app-folders/folders/Media]
name='Media'
apps=['com.github.neithern.g4music.desktop', 'mpv.desktop', 'org.gnome.Decibels.desktop', 'org.gnome.Showtime.desktop', 'org.gnome.Loupe.desktop']

[org/gnome/desktop/app-folders/folders/Utilities]
name='Utilities'
apps=['org.gnome.Calculator.desktop', 'org.gnome.clocks.desktop', 'org.gnome.Weather.desktop', 'org.gnome.Maps.desktop', 'org.gnome.Papers.desktop', 'org.gnome.TextEditor.desktop']
