# Virtual memory tuning for low idle RAM usage.

# Reclaim VFS dentries and inode cache more actively
vm.vfs_cache_pressure = 150

# Flush dirty pages in smaller increments to keep memory free
vm.dirty_ratio = 15
vm.dirty_background_ratio = 5
